name: build and test

on:
  pull_request:
    branches:
      - develop

env:
  APP_ENV: test

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache depencies
        uses: actions/cache@v2
        env:
          CACHE_NAME: cache-dependencies
        with:
          path: |
            vendor/
          key: ${{ env.CACHE_NAME }}-${{ hashFiles('composer.lock') }}

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Run App
        run: task install

      - name: Wait for service
        run: |
          while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker-compose ps -q php-fpm)")"; do
          case $status in
           starting) sleep 1;;
           healthy) exit 0;;
           unhealthy)
             docker-compose ps
             docker-compose logs php-fpm
             exit 1
           ;;
          esac
          done
          exit 1

      - name: Check App
        run: |
          echo "127.0.0.1 local.nine-circle.fr" | sudo tee -a /etc/hosts
          HTTP_CODE=$(curl -ik -X GET 'https://local.nine-circle.fr' -o /dev/null -w '%{http_code}\n' -s)
          if [ "$HTTP_CODE" = "200" ]; then
              exit 0
          fi
          docker-compose logs nginx
          exit 1

      #- name: Run Tests
      #  run: task ci

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: reports/
          retention-days: 1